from glob import glob
import json as j
import os
from Ver3StoreData import *

os.chdir(os.path.dirname(__file__))

files = glob("*/*.ffsd")

for fp in files:
	print(fp)
	f = open(fp, "rb")
	charinfo = Ver3CharInfo()
	Ver3StoreData.set_from_bytes(f.read(), charinfo)
	f.seek(0)
	dat = {"target": fp.replace("\\", "/"), "original": f.read().hex(), "testDatVer": 1}
	f.close()
	f = open(fp + ".test.json", "w")

	dat["mii_version"] = charinfo.get_mii_version()
	dat["face_type"] = charinfo.get_face_type()
	dat["face_color"] = charinfo.get_face_color()
	dat["face_tex"] = charinfo.get_face_tex()
	dat["face_make"] = charinfo.get_face_make()
	dat["hair_type"] = charinfo.get_hair_type()
	dat["hair_color"] = charinfo.get_hair_color()
	dat["hair_flip"] = charinfo.get_hair_flip()
	dat["eye_type"] = charinfo.get_eye_type()
	dat["eye_color"] = charinfo.get_eye_color()
	dat["eye_scale"] = charinfo.get_eye_scale()
	dat["eye_aspect"] = charinfo.get_eye_aspect()
	dat["eye_rotate"] = charinfo.get_eye_rotate()
	dat["eye_x"] = charinfo.get_eye_x()
	dat["eye_y"] = charinfo.get_eye_y()
	dat["eyebrow_type"] = charinfo.get_eyebrow_type()
	dat["eyebrow_color"] = charinfo.get_eyebrow_color()
	dat["eyebrow_scale"] = charinfo.get_eyebrow_scale()
	dat["eyebrow_aspect"] = charinfo.get_eyebrow_aspect()
	dat["eyebrow_rotate"] = charinfo.get_eyebrow_rotate()
	dat["eyebrow_x"] = charinfo.get_eyebrow_x()
	dat["eyebrow_y"] = charinfo.get_eyebrow_y()
	dat["nose_type"] = charinfo.get_nose_type()
	dat["nose_scale"] = charinfo.get_nose_scale()
	dat["nose_y"] = charinfo.get_nose_y()
	dat["mouth_type"] = charinfo.get_mouth_type()
	dat["mouth_color"] = charinfo.get_mouth_color()
	dat["mouth_scale"] = charinfo.get_mouth_scale()
	dat["mouth_aspect"] = charinfo.get_mouth_aspect()
	dat["mouth_y"] = charinfo.get_mouth_y()
	dat["mustache_type"] = charinfo.get_mustache_type()
	dat["beard_type"] = charinfo.get_beard_type()
	dat["beard_color"] = charinfo.get_beard_color()
	dat["beard_scale"] = charinfo.get_beard_scale()
	dat["beard_y"] = charinfo.get_beard_y()
	dat["glass_type"] = charinfo.get_glass_type()
	dat["glass_color"] = charinfo.get_glass_color()
	dat["glass_scale"] = charinfo.get_glass_scale()
	dat["glass_y"] = charinfo.get_glass_y()
	dat["mole_type"] = charinfo.get_mole_type()
	dat["mole_scale"] = charinfo.get_mole_scale()
	dat["mole_x"] = charinfo.get_mole_x()
	dat["mole_y"] = charinfo.get_mole_y()
	dat["height"] = charinfo.get_height()
	dat["build"] = charinfo.get_build()
	dat["name"] = bytearray(charinfo.get_name()).hex()
	dat["creator_name"] = bytearray(charinfo.get_creator_name()).hex()
	dat["gender"] = charinfo.get_gender()
	dat["birth_month"] = charinfo.get_birth_month()
	dat["birth_day"] = charinfo.get_birth_day()
	dat["favorite_color"] = charinfo.get_favorite_color()
	dat["favorite"] = charinfo.get_favorite()
	dat["copyable"] = charinfo.get_copyable()
	dat["ng_word"] = charinfo.get_ng_word()
	dat["localonly"] = charinfo.get_localonly()
	dat["region_move"] = charinfo.get_region_move()
	dat["font_region"] = charinfo.get_font_region()
	dat["room_index"] = charinfo.get_room_index()
	dat["position_in_room"] = charinfo.get_position_in_room()
	dat["birth_platform"] = charinfo.get_birth_platform()
	dat["create_id"] = charinfo.get_create_id().hex()
	dat["author_type"] = charinfo.get_author_type()
	dat["author_id"] = charinfo.get_author_id().hex()
 
	j.dump(dat, f, indent="\t")
	f.close()