from glob import glob
import json as j
import os
from Ver3StoreData import *

os.chdir(os.path.dirname(__file__))

files = glob("*/*.ffsd")

for fp in files:
	print(fp)
	f = open(fp, "rb")
	charinfo = Ver3CharInfo()
	Ver3StoreData.set_from_bytes(f.read(), charinfo)
	f.close()
	f = open(fp + ".test.json", "r")
	dat = j.load(f)

	assert dat["mii_version"] == charinfo.get_mii_version()
	assert dat["face_type"] == charinfo.get_face_type()
	assert dat["face_color"] == charinfo.get_face_color()
	assert dat["face_tex"] == charinfo.get_face_tex()
	assert dat["face_make"] == charinfo.get_face_make()
	assert dat["hair_type"] == charinfo.get_hair_type()
	assert dat["hair_color"] == charinfo.get_hair_color()
	assert dat["hair_flip"] == charinfo.get_hair_flip()
	assert dat["eye_type"] == charinfo.get_eye_type()
	assert dat["eye_color"] == charinfo.get_eye_color()
	assert dat["eye_scale"] == charinfo.get_eye_scale()
	assert dat["eye_aspect"] == charinfo.get_eye_aspect()
	assert dat["eye_rotate"] == charinfo.get_eye_rotate()
	assert dat["eye_x"] == charinfo.get_eye_x()
	assert dat["eye_y"] == charinfo.get_eye_y()
	assert dat["eyebrow_type"] == charinfo.get_eyebrow_type()
	assert dat["eyebrow_color"] == charinfo.get_eyebrow_color()
	assert dat["eyebrow_scale"] == charinfo.get_eyebrow_scale()
	assert dat["eyebrow_aspect"] == charinfo.get_eyebrow_aspect()
	assert dat["eyebrow_rotate"] == charinfo.get_eyebrow_rotate()
	assert dat["eyebrow_x"] == charinfo.get_eyebrow_x()
	assert dat["eyebrow_y"] == charinfo.get_eyebrow_y()
	assert dat["nose_type"] == charinfo.get_nose_type()
	assert dat["nose_scale"] == charinfo.get_nose_scale()
	assert dat["nose_y"] == charinfo.get_nose_y()
	assert dat["mouth_type"] == charinfo.get_mouth_type()
	assert dat["mouth_color"] == charinfo.get_mouth_color()
	assert dat["mouth_scale"] == charinfo.get_mouth_scale()
	assert dat["mouth_aspect"] == charinfo.get_mouth_aspect()
	assert dat["mouth_y"] == charinfo.get_mouth_y()
	assert dat["mustache_type"] == charinfo.get_mustache_type()
	assert dat["beard_type"] == charinfo.get_beard_type()
	assert dat["beard_color"] == charinfo.get_beard_color()
	assert dat["beard_scale"] == charinfo.get_beard_scale()
	assert dat["beard_y"] == charinfo.get_beard_y()
	assert dat["glass_type"] == charinfo.get_glass_type()
	assert dat["glass_color"] == charinfo.get_glass_color()
	assert dat["glass_scale"] == charinfo.get_glass_scale()
	assert dat["glass_y"] == charinfo.get_glass_y()
	assert dat["mole_type"] == charinfo.get_mole_type()
	assert dat["mole_scale"] == charinfo.get_mole_scale()
	assert dat["mole_x"] == charinfo.get_mole_x()
	assert dat["mole_y"] == charinfo.get_mole_y()
	assert dat["height"] == charinfo.get_height()
	assert dat["build"] == charinfo.get_build()
	assert dat["name"] == bytearray(charinfo.get_name()).hex()
	assert dat["creator_name"] == bytearray(charinfo.get_creator_name()).hex()
	assert dat["gender"] == charinfo.get_gender()
	assert dat["birth_month"] == charinfo.get_birth_month()
	assert dat["birth_day"] == charinfo.get_birth_day()
	assert dat["favorite_color"] == charinfo.get_favorite_color()
	assert dat["favorite"] == charinfo.get_favorite()
	assert dat["copyable"] == charinfo.get_copyable()
	assert dat["ng_word"] == charinfo.get_ng_word()
	assert dat["localonly"] == charinfo.get_localonly()
	assert dat["region_move"] == charinfo.get_region_move()
	assert dat["font_region"] == charinfo.get_font_region()
	assert dat["room_index"] == charinfo.get_room_index()
	assert dat["position_in_room"] == charinfo.get_position_in_room()
	assert dat["birth_platform"] == charinfo.get_birth_platform()
	assert dat["create_id"] == charinfo.get_create_id().hex()
	assert dat["author_type"] == charinfo.get_author_type()
	assert dat["author_id"] == charinfo.get_author_id().hex()

	f.close()